package persist

import (
	"fmt"
	"os"
	"strings"

	"github.com/krisk248/tuner/internal/profile"
)

// WriteSysctl generates and writes /etc/sysctl.d/99-tuner.conf for the given profile.
func WriteSysctl(p profile.Profile) error {
	v := p.Values

	var lines []string
	lines = append(lines, "# Generated by tuner - do not edit manually")
	lines = append(lines, fmt.Sprintf("# Profile: %s", p.Type))
	lines = append(lines, "")

	// Memory
	lines = append(lines, "# Memory")
	lines = append(lines, fmt.Sprintf("vm.swappiness = %d", v.Swappiness))
	lines = append(lines, fmt.Sprintf("vm.dirty_background_ratio = %d", v.DirtyBgRatio))
	lines = append(lines, fmt.Sprintf("vm.dirty_ratio = %d", v.DirtyRatio))
	lines = append(lines, fmt.Sprintf("vm.dirty_expire_centisecs = %d", v.DirtyExpire))
	lines = append(lines, fmt.Sprintf("vm.dirty_writeback_centisecs = %d", v.DirtyWriteback))
	lines = append(lines, fmt.Sprintf("vm.vfs_cache_pressure = %d", v.VFSCachePressure))
	lines = append(lines, "")

	// Network
	lines = append(lines, "# Network")
	lines = append(lines, fmt.Sprintf("net.ipv4.tcp_congestion_control = %s", v.TCPCongestion))
	lines = append(lines, fmt.Sprintf("net.ipv4.tcp_fastopen = %d", v.TCPFastOpen))
	lines = append(lines, fmt.Sprintf("net.ipv4.tcp_mtu_probing = %d", v.TCPMTUProbing))
	lines = append(lines, fmt.Sprintf("net.core.rmem_max = %d", v.RmemMax))
	lines = append(lines, fmt.Sprintf("net.core.wmem_max = %d", v.WmemMax))
	lines = append(lines, fmt.Sprintf("net.ipv4.tcp_rmem = %s", v.TCPRmem))
	lines = append(lines, fmt.Sprintf("net.ipv4.tcp_wmem = %s", v.TCPWmem))
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	return os.WriteFile(SysctlPath(), []byte(content), 0644)
}

// RemoveSysctl removes the tuner sysctl config.
func RemoveSysctl() error {
	err := os.Remove(SysctlPath())
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
