package persist

import (
	"fmt"
	"os"
	"strings"

	"github.com/krisk248/tuner/internal/detect"
	"github.com/krisk248/tuner/internal/profile"
)

// WriteUdev generates and writes /etc/udev/rules.d/99-tuner-disk.rules.
func WriteUdev(p profile.Profile) error {
	v := p.Values
	storage := detect.DetectStorage()

	var lines []string
	lines = append(lines, "# Generated by tuner - do not edit manually")
	lines = append(lines, fmt.Sprintf("# Profile: %s", p.Type))
	lines = append(lines, "")

	for _, disk := range storage.Disks {
		sched := v.IOScheduler(disk.Type)
		// udev rule to set scheduler
		lines = append(lines, fmt.Sprintf(
			`ACTION=="add|change", KERNEL=="%s", ATTR{queue/scheduler}="%s"`,
			disk.Name, sched,
		))
		if v.ReadAhead > 0 {
			lines = append(lines, fmt.Sprintf(
				`ACTION=="add|change", KERNEL=="%s", ATTR{queue/read_ahead_kb}="%d"`,
				disk.Name, v.ReadAhead,
			))
		}
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")
	return os.WriteFile(UdevPath(), []byte(content), 0644)
}

// RemoveUdev removes the tuner udev rules.
func RemoveUdev() error {
	path := UdevPath()
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	return os.Remove(path)
}
